"""Readable, self-contained web report with precomputed window comparisons."""
import base64,csv,html,json

AUTHORS='Theo Del Compare y Santiago Romero'
AUTHORS_HTML='<a href="mailto:Theo.Del.Compare@gmail.com">Theo Del Compare</a> y <a href="mailto:romerosantiago545@gmail.com">Santiago Romero</a>'

def table(headers,rows):
    esc=lambda x:html.escape(str(x))
    return '<div class="tablewrap"><table><thead><tr>'+''.join('<th scope="col">'+esc(x)+'</th>' for x in headers)+\
        '</tr></thead><tbody>'+''.join('<tr>'+''.join('<td>'+esc(x)+'</td>' for x in row)+'</tr>' for row in rows)+'</tbody></table></div>'

def image(figdir,name,caption):
    encoded=base64.b64encode((figdir/name).read_bytes()).decode('ascii')
    return f'<figure><img src="data:image/png;base64,{encoded}" alt="{html.escape(caption)}"><figcaption>{html.escape(caption)}</figcaption></figure>'

def document(p,c,figdir):
    fmt=lambda x,n=3:f'{x:.{n}f}'.replace('.',',')
    fit=p['fit'];ci=fit['intervals_us'];nn=c['network_validation'];composition=c['composition']
    root=figdir.parent.parent
    with (root/'data/derived/upper_window_comparison.csv').open(encoding='utf-8',newline='') as f:windows=list(csv.DictReader(f))
    window_options=''.join('<option value="'+str(i)+'"'+(' selected' if row['variant']=='record_minus10' else '')+'>'+html.escape(row['label'])+'</option>' for i,row in enumerate(windows))
    filters=table(['Criterio','Regla utilizada'],[
        ['Base y ruido','Mediana y 1,4826 MAD fuera de 160–300 ns; recorte robusto para estimar la base, sin modificar las muestras'],
        ['Semilla negativa','Altura ≥max(45 mV, 3σ); prominencia ≥max(30 mV, 2,5σ); separación ≥5 ns'],
        ['Pulso aceptado','Amplitud ≥max(80 mV, 4,5σ); ancho de 3–35 ns a mitad de altura; al menos dos muestras'],
        ['Coincidencia inicial','CH1/CH2 en 170–270 ns; separación ≤15 ns'],
        ['Fallos de calidad','Ruido excesivo, base saturada, impulso aislado y oscilación; conservar marcas de deriva, saturación local y borde'],
        ['Secundario para vida media','Tiempo obtenido de CH2/CH3; CH1 tardío no veta ni determina el retardo']])
    decisions=table(['Decisión sobre las señales independientes','Número'],[
        ['Seleccionadas para el ajuste',525],['CH3 inicial detectado',212],['CH3 inicial incierto',41],
        ['Calidad inicial pendiente',8],['Bajo 120 ns',44],['Exclusión explícita tras revisión',8],
        ['Calidad aprobada sin tiempo utilizable',7],['Fuera por el margen final',2],['Total',847]])
    inventory=table(['Adquisición de septiembre','Registros'],[
        ['3 de septiembre, primera corrida','5019'],['3 de septiembre, segunda corrida','156'],
        ['4 de septiembre','64 038'],['7 de septiembre','85 843'],['9 de septiembre','37 624'],
        ['Total de las cinco corridas','192 680'],['Adquisición independiente sin fecha conservada','847']])
    methods=table(['Clase propuesta','Criterio de las reglas'],[
        ['Muón largo','Longitud ≥30 píxeles físicos; ancho/longitud ≤0,10; sagita/longitud ≤0,03; rectitud ≥0,75'],
        ['Muón corto','Recta de 7–30 píxeles, o 15–30 con columnas agrupadas, dentro de la banda energética de las trazas largas del mismo tipo'],
        ['Depósito puntual','Longitud ≤7 píxeles; subdivisión a 600 eV como convención de clases'],
        ['Alfa','Depósito compacto, redondeado y de energía aproximada ≥1 MeV; la saturación limita su reconstrucción'],
        ['Artefacto','Línea de registro serie o columna anómala; trazas horizontales cortas sin difusión y sin energía compatible con una MIP'],
        ['Electrón','Resto de trazas curvas o irregulares según las reglas; no es una identificación física independiente']])
    calibration=table(['Amplificador','Ganancia [ADU/e⁻]','Ruido [e⁻]'],[
        [i+1,f'{g} ± {sg}',f'{fmt(n)} ± {fmt(sn)}'] for i,(g,sg,n,sn) in
        enumerate(zip(composition['gain_adu_per_e'],composition['gain_std'],composition['noise_e'],composition['noise_std']))])
    metrics=table(['Clase','mAP50','Precisión','Recuperación (recall)'],[
        [name,fmt(nn[k]['map50'],2),fmt(nn[k]['precision'],2),fmt(nn[k]['recall'],2)]
        for k,name in [('artefacto','Artefacto'),('muon','Muón'),('electron','Electrón'),('puntual','Puntual')]]+
        [['Alfa (nueve casos de referencia)','≈0','No informada','0']])
    comparison=table(['Aspecto','Centelladores','Skipper-CCD'],[
        ['Qué se observa','Pulsos y retardos','Posición, forma y carga de trazas'],
        ['Unidad principal','ns y mV; ajuste en µs','Píxeles físicos, electrones y keV'],
        ['Método','Base robusta, pulsos, coincidencias y revisión humana','Calibración, agrupación de píxeles, reglas y red'],
        ['Resultado','525 retardos; τ=1,948 µs','6251 trazas en 30 imágenes; 1316 etiquetas de muón'],
        ['Validación','Revisión y simulaciones condicionales','Calibración y acuerdo con etiquetas automáticas'],
        ['Límite','Ventana y aceptación temporal no calibrada','Ambigüedad física de clases y exposición inferida']])
    body=f'''
<section id="s1"><p class="eyebrow">01 · OBJETIVO DEL PROYECTO</p><h2>Un proyecto, dos maneras de observar muones</h2>
<p>El proyecto analiza señales de partículas ionizantes, particularmente muones, con mediciones realizadas mediante instrumental de un laboratorio de enseñanza y datos de un detector profesional proporcionados por el Laboratorio Lambda. En los centelladores se identifican pulsos y coincidencias, se seleccionan secundarios separados y se estima una escala de decaimiento. En el Skipper-CCD se reconstruyen depósitos de carga y se clasifican trazas a partir de forma, energía y una red neuronal.</p>
<p>La comparación examina qué permite observar cada técnica, cómo se seleccionan las señales y qué sostienen sus validaciones e incertidumbres. Se espera obtener información temporal y espacial complementaria, manteniendo separados los conjuntos de datos y sus criterios.</p>
<p>En un decaimiento del muón aparece una partícula cargada, electrón o positrón, junto con neutrinos. La presencia de un secundario separado motiva su búsqueda en las formas de onda. Una traza larga y recta motiva una etiqueta de muón en el CCD. Ninguna de esas firmas, por sí sola, certifica la identidad de la partícula.</p>
<div class="note">Los conteos del CCD no se suman a la muestra de retardos: esas imágenes integran carga y no proporcionan los tiempos necesarios para el ajuste de vida media.</div></section>

<section id="s2"><p class="eyebrow">02 · LABORATORIO DE ENSEÑANZA</p><h2>Montaje, adquisición y filtros</h2>
<h3>Disposición confirmada</h3><p>Se utilizan tres centelladores, superior, central e inferior, conectados a CH1, CH2 y CH3. Una barra de <strong>plomo</strong> está entre el central y el inferior. CH1 dispara la adquisición y se exige también señal en CH2 para guardar un evento. No se exige CH3. Las dimensiones de la barra y de los centelladores no están disponibles.</p>
<h3>Estructura de los registros</h3><p>Se usan exclusivamente <strong>1024 muestras</strong> por registro, con tiempo en ns y tres canales en mV. La ventana exportada va de 0 a 1698,340 ns, con paso aproximado de 1,660 ns. Se comprobaron estructura, finitud, monotonicidad y duplicados. Los registros de 300 puntos quedaron fuera del análisis. El eje compartido exportado no demuestra por sí solo la calibración relativa entre canales.</p>
<p>Las cinco corridas previas reúnen 192 680 registros. Una adquisición independiente agregó 847 señales guardadas por presentar un pico secundario apartado; no conserva fecha ni la lógica exacta de preselección. El ajuste final se centra exclusivamente en esta última adquisición.</p>
<details><summary>Inventario por fecha y alcance de la adquisición</summary>{inventory}<p>No se reconstruyeron registros faltantes ni se tomó la rotación de archivos como tiempo vivo. Las marcas de reloj no se usan para medir el retardo entre pulsos. El rechazo de voltajes positivos durante adquisición no tiene una condición exacta documentada; no se vuelve a aplicar un veto inventado.</p></details>
<h3>Detección de pulsos</h3><p>La base se estima por mediana y el ruido mediante una escala robusta basada en la MAD. No se suavizan ni se reemplazan las muestras. La altura, prominencia, separación y forma permiten distinguir picos de fluctuaciones, impulsos aislados y oscilaciones.</p>{filters}
{image(figdir,'signals.png','Formas de onda originales alrededor del secundario, descritas por su morfología. La banda sombreada señala el margen final de 10 ns.')}
<p>Una <strong>semilla débil</strong> es una detección preliminar que no supera todos los cortes automáticos de calidad o conserva alguna marca. No implica necesariamente una señal falsa: un grupo puede contener un pulso claro y otra semilla débil. Los grupos mixtos aprobados tras revisión entran con los tiempos de CH2/CH3 ya asignados. Las marcas de saturación, borde y calidad permanecen en los registros técnicos.</p>
<p>Para vida media se exige coincidencia inicial aceptada y CH3 inicial no detectado sobre umbral. CH1 tardío no veta el evento ni aporta el tiempo del secundario. La selección para conteo, la selección de eficiencia y la selección temporal tienen objetivos distintos; exigir CH2 durante adquisición impide estimar directamente su eficiencia con esa misma muestra.</p></section>

<section id="s3"><p class="eyebrow">03 · ANÁLISIS TEMPORAL</p><h2>Selección final y estimación de vida media</h2>
<p>Las 847 señales independientes mantienen una decisión trazable, incluyendo los casos aún pendientes. Ningún evento de las primeras corridas interviene en el ajuste final.</p>{decisions}
<p>De los 88 casos revisados, se aprobaron 80 y se excluyeron ocho. Bajo la ventana final, 67 aprobados aportan un retardo; cuatro están bajo el mínimo, dos en el borde y siete no tienen un tiempo secundario utilizable. Aprobar la forma de una señal no permite inventar el tiempo que falta. Las 41 dudas sobre CH3 inicial y ocho de calidad inicial siguen identificadas.</p>
<h3>Por qué el registro requiere un límite superior</h3><p>La cota inferior de 120 ns limita problemas de separación del pulso inicial. La cota superior se obtiene del final de cada registro, después de descontar el instante inicial de CH1 y un margen de 10 ns. No se prolonga una traza hasta infinito: un decaimiento posterior al final no puede observarse. Los límites superiores de la muestra seleccionada están entre 1,461 y 1,492 µs.</p>
<p class="equation">a = 0,120 µs &nbsp;·&nbsp; Uᵢ = T<sub>final,i</sub> − T<sub>CH1,i</sub> − 0,010 µs<br>p(tᵢ | τ, Uᵢ) = exp(−tᵢ/τ) / {{τ [exp(−a/τ) − exp(−Uᵢ/τ)]}}</p>
<p>Se maximiza la verosimilitud de los <strong>tiempos individuales</strong>, con fondo fijado en cero y peso uno por evento. La normalización usa la ventana de cada registro. La media de los tiempos truncados no estima directamente τ. El histograma no determina el resultado del ajuste.</p>
{image(figdir,'lifetime.png','525 retardos y predicción integrada por ventanas individuales, en intervalos de 80 ns. La caída del último intervalo incluye el efecto del final de los registros.')}
<div class="result"><strong>τ = {fmt(fit['tau_us'])} µs</strong><p>Intervalo estadístico nominal del 68 %: [{fmt(ci['68'][0])}; {fmt(ci['68'][1])}] µs.<br>Intervalo del 95 %: [{fmt(ci['95'][0])}; {fmt(ci['95'][1])}] µs.</p></div>
<p>Estos intervalos de perfil expresan incertidumbre por tamaño finito bajo el modelo. No incluyen incertidumbres de aceptación, calibración o selección durante adquisición. El resultado es compatible con los aproximadamente 2,197 µs de la edición histórica del PDG utilizada como referencia; esa compatibilidad no certifica pureza ni ausencia de sesgos.</p>
<details><summary>Explorar la sensibilidad al límite superior</summary><p>Los siguientes ajustes conservan las decisiones de calidad y cambian la ventana. Son comparaciones precomputadas; la elección adoptada sigue siendo el final individual menos 10 ns.</p><label for="window-choice">Ventana comparada</label><select id="window-choice">{window_options}</select><div id="window-result" aria-live="polite"></div><p>La extensión de la cola sumó señales limpias y aprobadas. Se eligió el margen de 10 ns para evitar dos colas incompletas, sin buscar el valor más próximo a una referencia.</p></details>
<h3>Controles de coincidencias accidentales</h3><p>En las cinco corridas anteriores se compararon ventanas pareadas de 120–170 ns: tres secundarios anteriores y 15 posteriores en 87 915 padres elegibles. El intervalo anterior corto y la posible respuesta instrumental tardía limitan extrapolar ese control. No calibra el fondo de la muestra independiente, ya preseleccionada por secundario. El control triple es descriptivo, no una muestra de fondo puro; no se resta al ajuste final.</p>
<div class="note">Fondo cero es una hipótesis de este ajuste. Normalizar el registro corrige su truncación geométrica, pero no una aceptación desconocida que cambie con el retardo.</div></section>

<section id="s4"><p class="eyebrow">04 · DETECTOR PROFESIONAL</p><h2>Desarrollo y análisis del detector con datos del Laboratorio Lambda</h2>
<p>El Laboratorio Lambda proporcionó los datos del detector Skipper-CCD, que mide la carga depositada en silicio mediante lecturas repetidas no destructivas. La bibliografía del instrumento de Atucha-II se utiliza como referencia de geometría y modo de lectura; esa comparación no certifica la ubicación ni la identidad del detector de origen. Se documentaron 492 imágenes científicas de 2025 y nueve imágenes de control de 2020, con cuatro amplificadores por imagen. Los formatos FITS y ROOT de las nueve imágenes de control son exportaciones equivalentes, no 18 exposiciones independientes.</p>
<p>El sensor tiene píxeles de 15 × 15 µm² y 675 µm de espesor. El conjunto científico agrupa diez columnas por lectura, mientras el de control no usa ese agrupamiento. Se realizan 300 lecturas por píxel: este número corresponde al sensor y no a los registros de 300 puntos descartados en centelladores. La exposición media de 32–37 min fue inferida y no se trata como tiempo vivo confirmado.</p>
<h3>De unidades del sensor a energía</h3><p>Se resta el pedestal por fila a partir del overscan, se estima su ruido con la MAD y se ajusta la ganancia a los picos de cero, uno y más electrones. Se enmascaran columnas anómalas y datos no finitos. La carga se expresa en electrones y se convierte a energía con 3,75 eV por par electrón-hueco. En imágenes exportadas sin calibración, la intensidad puede usarse para geometría, pero no se informa como energía física.</p>
<h3>Agrupación de píxeles y etiquetas</h3><p>Una semilla de al menos 20 electrones inicia la traza; píxeles conectados por encima de cuatro electrones permiten extenderla. El corte total habitual es de 60 electrones, equivalente a 225 eV. La geometría corrige el agrupamiento de columnas. Las rectas dominantes se separan de trazas que las cruzan y se unen segmentos colineales a través de huecos o columnas enmascaradas.</p>{methods}
{image(figdir,'ccd_detections.png','Ilustración conservada del análisis previo en dos amplificadores. Las cajas representan clases propuestas por el algoritmo: muón, electrón, alfa, depósito puntual y artefacto. No constituyen identificación física independiente.')}
<p>El sistema usa reglas para generar etiquetas y entrena YOLO11n con aproximadamente cien mil trazas. La entrada combina energía logarítmica, energía lineal y una máscara de carga. En el método híbrido, los píxeles y la energía provienen de la reconstrucción; la red aporta una clase cuando su caja se superpone al menos 0,3 con la traza, y las reglas completan las trazas sin caja asociada. El modo automático usa las reglas en imágenes sin agrupamiento de columnas, donde la red tiene menos ejemplos de entrenamiento.</p></section>

<section id="s5"><p class="eyebrow">05 · RESULTADOS ESPACIALES</p><h2>Composición, calibración y validación del clasificador</h2>
<p>El resumen conservado de <strong>30 imágenes</strong> contiene <strong>6251 trazas</strong>: 2963 electrones, 1712 depósitos puntuales, 1316 muones y 260 artefactos según las etiquetas del análisis. No aparecen alfas en este resumen. Esta composición es distinta de los conjuntos usados para validar la red y comparar métodos.</p>
{image(figdir,'ccd_composition.png','Fracciones de etiquetas en el subconjunto de 30 imágenes. Los porcentajes no son fracciones físicas corregidas por eficiencia o pureza.')}
<h3>Contrastes de la escala de energía</h3><p>La masa activa calculada fue de 2,2167 g, próxima a los 2,22 g publicados. El análisis previo documentó una estructura de fluorescencia del cobre alrededor de 8 keV como contraste de la calibración. Las trazas etiquetadas como muones presentaron un máximo cercano a 400 keV y una mediana de 496 keV. Son resúmenes de energía depositada y no mediciones temporales.</p>
<details><summary>Ganancia y ruido por amplificador</summary>{calibration}<p>Los valores son medias y dispersiones entre las 30 imágenes. Las dispersiones no representan todos los sistemáticos de la escala de energía. Saturación y carga perdida en columnas enmascaradas pueden subestimar los depósitos.</p></details>
<h3>Modelo v2: 300 imágenes y 15 434 trazas de referencia</h3>{metrics}
<p><strong>mAP50</strong> es una medida de precisión promedio al comparar cajas con superposición mínima del 50 %. La precisión estima qué fracción de las detecciones coincide con las etiquetas; la recuperación indica qué fracción de las etiquetas encuentra el modelo. Aquí la referencia proviene de reglas automáticas: estas métricas miden acuerdo con ellas, no pureza física.</p>
<p>Entre versiones, la fracción llamada muón en los 446 muones cortos de referencia pasó del 1 al 31 %. Los muones largos se mantuvieron cerca del 87–88 %. La energía por recorrido, importante para trazas cortas, solo llega de manera indirecta a la red. Las alfas tienen nueve casos de referencia en validación y no se aprendieron adecuadamente.</p>
<h3>Método híbrido: otra comparación</h3><p>En 75 archivos con 15 554 trazas, el acuerdo con las reglas mejoró del 78 al 80 % para muones, del 79 al 86 % para electrones, del 91 al 98 % para puntuales y del 85 al 89 % para artefactos. La unión de segmentos redujo de 55 a ocho los candidatos a muón fragmentados en los conjuntos examinados. Estas cifras no se presentan como la misma métrica ni el mismo denominador que la validación de 300 imágenes.</p></section>

<section id="s6"><p class="eyebrow">06 · DISCUSIÓN Y VALIDACIÓN</p><h2>Qué sostienen los resultados</h2>{comparison}
<h3>Comprobaciones de la etapa temporal</h3><p>Pasaron 31 pruebas de código sobre lectura, alcance, pulsos, ventanas, pesos y verosimilitud. La verificación previa contra las muestras originales comprobó las 847 señales y los 525 tiempos usados. El ajuste compacto conserva exactamente esa selección. La revisión visual es no ciega y no mide pureza experimental.</p>
<p>Se repitieron 3000 simulaciones condicionales con 525 retardos y τ generador de 1,947766 µs. Las coberturas locales del 68 y 95 % fueron de 67,77 y 94,87 %, con p=0,786 para una comprobación de distribución con reajuste. Son listas artificiales bajo el modelo; no son nuevas mediciones ni simulan toda la electrónica. Las inyecciones en fondos reales examinan recuperación del algoritmo según forma, amplitud y retardo, sin constituir una eficiencia universal.</p>
<h3>Límites de interpretación</h3><p>En los centelladores quedan incertidumbres de aceptación temporal, preselección, calibración relativa y respuestas tardías de electrónica. No se distinguen las cargas del muón ni se cuantifica una posible captura de muones negativos en los materiales. Por eso la escala ajustada no se presenta como una medición certificada de la vida media libre.</p>
<p>En el CCD, un electrón energético recto puede reproducir la firma geométrica de un muón. Las bandas energéticas de trazas cortas difieren entre configuraciones, los alfas son escasos y la exposición efectiva sigue inferida. La comparación previa con un flujo cósmico estimado dejó una discrepancia de aproximadamente un factor cuatro, sin cuantificar completamente techo, blindaje y aceptación; no se convierte en eficiencia medida.</p>
<p>El proyecto concluye esta etapa con una estimación temporal condicionada y una herramienta de reconstrucción y clasificación espacial. Ambas aportan evidencia complementaria sobre señales compatibles con muones, conservando decisiones y limitaciones.</p></section>

<section id="s7"><p class="eyebrow">07 · PROCEDENCIA Y REPRODUCCIÓN</p><h2>Una entrega verificable</h2>
<p>La parte temporal conserva tiempos, ventanas, decisiones y hashes. La parte del CCD integra código, bitácora, figuras y resúmenes de la rama del detector. No están disponibles las imágenes originales ni las tablas completas de validación del CCD: esta revisión comprueba consistencia documental y no afirma una nueva ejecución de calibración, entrenamiento o métricas.</p>
<p>El HTML incorpora sus cuatro figuras y puede leerse sin conexión. La exploración de ventanas usa resultados ya calculados. El PDF tiene una presentación académica independiente y se genera mediante LaTeX, con su fuente y figuras preparados para compilar. La documentación técnica conserva los criterios y la procedencia de cada decisión.</p>
<p><a href="pdf/proyecto_muones.pdf">Descargar el PDF de cinco páginas</a> · <a href="../docs/REPRODUCIBILIDAD.md">Procedimiento de reproducción</a> · <a href="../docs/INTEGRACION_DOS_ANALISIS.md">Procedencia de la integración</a></p>
<h3>Reconocimiento de asistencia de IA</h3><p>Este trabajo se realizó con ayuda de Claude (Anthropic) y Codex (OpenAI) para desarrollar código, revisar el análisis y elaborar los informes. Las decisiones y la interpretación final corresponden a los autores.</p>
<h3>Referencias</h3><ol class="references">
<li>T. Del Compare, L. Pellegrino y S. Romero. <em>Guía de la práctica de muones</em>, Grupo 9, Laboratorio 5, FCEN-UBA; material docente aportado.</li>
<li>K. Nakamura et al. (PDG), J. Phys. G 37, 075021 (2010), actualización 2011: <a href="https://pdg.lbl.gov/2011/listings/rpp2011-list-muon.pdf">hoja del muón, página 2</a>.</li>
<li>E. Depaoli et al. <em>Deployment and performance of a Low-Energy-Threshold Skipper-CCD inside a nuclear reactor</em>. JHEP 10 (2024) 155. <a href="https://doi.org/10.1007/JHEP10(2024)155">Artículo del instrumental</a>.</li>
<li>J. Tiffenberg et al. <em>Single-electron and single-photon sensitivity with a silicon Skipper CCD</em>. PRL 119 (2017) 131802. <a href="https://arxiv.org/abs/1706.00028">Artículo</a>.</li>
<li>SciPy: <a href="https://docs.scipy.org/doc/scipy/reference/generated/scipy.signal.find_peaks.html">documentación de find_peaks</a>.</li>
<li>F. Gray. <em>Muon Capture on the Proton and Deuteron</em> (2008). <a href="https://arxiv.org/abs/0808.1544">Artículo</a>.</li>
<li>T. Del Compare y S. Romero: <a href="https://github.com/santii-romero/Deteccion-de-muones">repositorio del proyecto</a>, análisis temporal en main y detector en identificador.</li></ol></section>'''
    css='''
:root{--ink:#223846;--muted:#5b707e;--blue:#285b78;--orange:#b95330;--line:#d9e3e9}*{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;color:var(--ink);background:#edf2f5;font:17px/1.7 system-ui,sans-serif}main{max-width:1120px;margin:0 auto;background:#fff;padding:40px 54px 55px}header{padding:15px 0 30px;border-bottom:3px solid var(--orange)}h1{font-size:clamp(31px,4vw,49px);line-height:1.12;max-width:890px;margin:16px 0}h2{font-size:30px;line-height:1.2;margin:8px 0 18px}h3{font-size:21px;margin:24px 0 8px}p{margin:12px 0}.eyebrow{font-size:12px;font-weight:700;letter-spacing:.1em;color:var(--muted)}.authors{font-size:19px}.lead{font-size:20px;max-width:840px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:12px;margin:28px 0 10px}.card{padding:17px;background:#eff5f8;border:1px solid var(--line);border-radius:6px}.card strong{display:block;font-size:27px}.card span{font-size:14px;color:var(--muted)}nav{display:flex;gap:16px;flex-wrap:wrap;font-size:14px;padding:20px 0;border-bottom:1px solid var(--line)}a{color:#245b82}section{padding:35px 0 20px;border-bottom:1px solid var(--line);scroll-margin-top:15px}figure{margin:24px 0}img{display:block;width:100%;height:auto}figcaption{font-size:14px;line-height:1.5;color:var(--muted);margin-top:10px}.tablewrap{overflow-x:auto;margin:18px 0}table{width:100%;border-collapse:collapse;font-size:15px;line-height:1.5}th{text-align:left;background:#e7f0f5}td,th{padding:10px 12px;border-bottom:1px solid var(--line);vertical-align:top}tr:nth-child(even){background:#f7f9fa}.note,.equation,.result{padding:17px 21px;margin:20px 0;background:#f1f6f9;border-left:3px solid var(--blue)}.equation{font-family:Georgia,serif;font-size:18px;overflow-wrap:anywhere}.result{background:#fff4ed;border-color:var(--orange)}.result>strong{font-size:28px}details{padding:15px 18px;border:1px solid var(--line);border-radius:5px;margin:18px 0}summary{font-weight:600;cursor:pointer}label{display:block;margin-top:15px}select{font:inherit;padding:9px;margin:8px 0;width:100%;max-width:430px;border:1px solid #93a9b6;border-radius:4px}#window-result{padding:15px;background:#edf3f6;margin-top:10px}.references{font-size:14px;line-height:1.6;padding-left:24px}.references li{margin-bottom:8px}footer{font-size:13px;color:var(--muted);margin-top:25px}@media(max-width:650px){main{padding:24px 18px}body{font-size:16px}.cards{grid-template-columns:1fr}h2{font-size:25px}.card strong{font-size:23px}td,th{padding:8px}}@media print{body{background:#fff}main{max-width:none;padding:0}nav{display:none}details{break-inside:avoid}a{color:inherit}}
'''
    window_json=json.dumps(windows,ensure_ascii=False).replace('</','<\\/')
    script='''const comparisons='''+window_json+''';const choice=document.getElementById('window-choice');const panel=document.getElementById('window-result');function updateWindow(){const v=comparisons[Number(choice.value)];const f=x=>Number(x).toFixed(3).replace('.',',');panel.textContent=`${v.events} eventos · τ = ${f(v.tau_us)} µs · intervalo nominal 68 %: [${f(v.lower68_us)}; ${f(v.upper68_us)}] µs`;}choice.addEventListener('change',updateWindow);updateWindow();'''
    nav=''.join(f'<a href="#s{i}">{name}</a>' for i,name in enumerate(['Proyecto','Centelladores','Vida media','CCD','Resultados CCD','Discusión','Referencias'],1))
    return '<!doctype html><html lang="es"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Muones: centelladores y Skipper-CCD</title><style>'+css+'</style></head><body><main><header><p class="eyebrow">LABORATORIO 5 · INFORME CONJUNTO</p><h1>Muones: análisis temporal y espacial</h1><p class="authors">'+AUTHORS_HTML+'</p><p class="lead">Señales de un laboratorio de enseñanza y trazas en un detector profesional Skipper-CCD.</p><div class="cards"><div class="card"><strong>525 retardos</strong><span>Selección final para vida media</span></div><div class="card"><strong>'+fmt(fit['tau_us'])+' µs</strong><span>Exponencial condicionada a cada registro</span></div><div class="card"><strong>6251 trazas</strong><span>Resumen del CCD en 30 imágenes</span></div></div></header><nav aria-label="Secciones del informe">'+nav+'</nav>'+body+'<footer>Integrantes: '+AUTHORS_HTML+'. Resultados y documentación técnica acompañan el proyecto.</footer></main><script>'+script+'</script></body></html>'
